services:
  redis:
    image: redis:7-alpine
    container_name: bitwarden-backup-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - bitwarden-backup-network

  bitwarden-backup-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: bitwarden-backup-api
    ports:
      - "5050:5050"
    volumes:
      - .:/app:rw
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379/0
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - bitwarden-backup-network

networks:
  bitwarden-backup-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
