services:
  bitwarden-backup:
    image: nikhilbadyal/bitwarden-backup
    container_name: bitwarden-backup
    volumes:
      - .:/app:rw
    env_file:
      - .env
    environment:
      - BACKUP_DIR=/tmp/bw_backup  # Override for Docker container
      - BITWARDENCLI_APPDATA_DIR=/tmp/bw_appdata  # Bitwarden CLI data directory in writable tmpfs
    pull_policy: always
    restart: "no"  # Don't restart automatically for backup jobs
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
