services:
  bitwarden-backup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitwarden-backup
    volumes:
      - .:/app:rw
    env_file:
      - .env
    environment:
      - BACKUP_DIR=/tmp/bw_backup  # Override for Docker container
    command: >
      sh -c "
        chmod +x /app/*.sh /app/scripts/*.sh &&
        /app/setup-rclone.sh &&
        /app/scripts/backup.sh
      "
