services:
  bitwarden-backup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitwarden-backup
    volumes:
      - .:/app:rw
    env_file:
      - .env
    environment:
      - BACKUP_DIR=/tmp/bw_backup  # Override for Docker container
