[tool.ruff]
line-length = 120
target-version = "py311"
fix = true
show-fixes = true
[tool.ruff.lint]
select = [ "ALL"]
ignore = [
    "S603", # `subprocess` call: check for execution of untrusted input
    "S607", # Starting a process with a partial executable path
    "BLE001", # Audit URL open for permitted schemes.
    "D104", # Audit URL open for permitted schemes.
    "D100", # Audit URL open for permitted schemes.
]
[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.docformatter]
recursive = true
wrap-summaries = 120
wrap-descriptions = 120

[tool.black]
line-length = 120

[pycodestyle]
max-line-length = 120
exclude = ["venv"]


[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true

[tool.isort]
line_length = 120
skip = ["venv"]
profile = "black"
