name: Bitwarden Backup

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      debug_session:
        description: 'Run a tmate debug session'
        required: false
        type: boolean
        default: false

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Create .env file from secret
        run: |
          echo "${{ secrets.BITWARDEN_BACKUP_ENV }}" > .env
          # For debugging (don't show in logs)
          echo "::add-mask::$(head -n 3 .env)"
          echo "Generated .env file with $(wc -l .env | awk '{print $1}') variables"

      - name: Tmate debugging session
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.debug_session == true
        uses: mxschmitt/action-tmate@v3

      - name: Set up Docker Compose
        if: github.event.inputs.debug_session != true
        run: |
          docker compose version

      - name: Run pre-commit shellcheck
        if: github.event.inputs.debug_session != true
        run: |
          pip install pre-commit
          pre-commit run -a

      - name: Run backup with compose
        if: github.event.inputs.debug_session != true
        run: |
          docker compose -f docker-compose.yml up --build --force-recreate

      - name: Save logs
        if: always() && github.event.inputs.debug_session != true
        run: |
          mkdir -p logs
          docker compose logs > logs/backup-$(date +%Y%m%d-%H%M%S).log 2>&1 || true

      - name: Upload logs artifact
        if: always() && github.event.inputs.debug_session != true
        uses: actions/upload-artifact@v4.6.2
        with:
          name: backup-logs
          path: logs/
      - name: Clean up .env file
        if: always()
        run: rm -f .env
