name: Push Base Image to DockerHub
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dockerhub-push:
    uses: nikhilbadyal/ghactions/.github/workflows/dockerhub-push.yml@main
    with:
      IMAGE_TAG: ${{ github.repository }}:latest
      FILE: Dockerfile
      PUSH_DESCRIPTION: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
