name: Lint

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run -a
